--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--
--  Insert statements for the master data in the Unipoole database.
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--

--------------------------------------------------------
--  Base data insert for Table UNI_DEVICE_REG
--------------------------------------------------------
DELETE FROM UNI_DEVICE_REG WHERE ID = 1;
INSERT INTO UNI_DEVICE_REG (ID, USERNAME, DEVICE_ID, ACTIVE, LAST_UPDATED) VALUES(
    1, '_UNIPOOLE', 'MASTER', 1, CURRENT_DATE);
SELECT UNI_DEVICE_REG_SEC.nextval FROM dual;
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
