-- Script to delete a specific client creation data from the database.
-- This will also delete any versions that has been created
-- MAKE SURE UNIPOOLE_SERVICE IS STOPPED BEFORE USING THIS!


-- Delete all content releases versions
-- SELECT * FROM UNI_CONTENT_RELEASE_VERSION WHERE CONTENT_RELEASE_ID IN (SELECT ID FROM UNI_CONTENT_RELEASE WHERE MODULE_ID LIKE 'AFL1501-13-S1%');
DELETE UNI_CONTENT_RELEASE_VERSION WHERE CONTENT_RELEASE_ID IN (SELECT ID FROM UNI_CONTENT_RELEASE WHERE MODULE_ID LIKE 'OCT1501-16-S1%');

-- Delete all content releases
-- SELECT * FROM UNI_CONTENT_RELEASE WHERE MODULE_ID LIKE 'AFL1501-13-S1%';
DELETE UNI_CONTENT_RELEASE WHERE MODULE_ID LIKE 'OCT1501-16-S1%';

-- Delete all content version for a module
-- SELECT * FROM UNI_CONTENT_VERSION WHERE MODULE_REGISTRATION_ID IN (SELECT ID FROM UNI_MODULE_REG WHERE MODULE_ID LIKE 'AFL1501-13-S1%');
DELETE UNI_CONTENT_VERSION WHERE MODULE_REGISTRATION_ID IN (SELECT ID FROM UNI_MODULE_REG WHERE MODULE_ID LIKE 'OCT1501-16-S1%');

-- Delete all module registrations
-- SELECT * FROM UNI_MODULE_REG WHERE MODULE_ID LIKE 'AFL1501-13-S1%';
DELETE UNI_MODULE_REG WHERE MODULE_ID LIKE 'OCT1501-16-S1%';


-- Delete all managed modules
-- SELECT * FROM UNI_MANAGED_MODULE WHERE MODULE_ID LIKE 'AFL1501-13-S1%';
DELETE UNI_MANAGED_MODULE WHERE MODULE_ID LIKE 'OCT1501-16-S1%';

COMMIT