--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--
--  Drop statements for all objects in the Unipoole database
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--
DROP TABLE UNI_CONTENT_RELEASE_VERSION;
DROP SEQUENCE UNI_CONTENT_REL_VERSION_SEC;
DROP TABLE UNI_CONTENT_RELEASE;
DROP SEQUENCE UNI_CONTENT_RELEASE_SEC;
DROP TABLE UNI_CODE_RELEASE_VERSION;
DROP SEQUENCE UNI_CODE_RELEASE_VERSION_SEC;
DROP TABLE UNI_CODE_RELEASE;
DROP SEQUENCE UNI_CODE_RELEASE_SEC;
DROP TABLE UNI_CONTENT_VERSION;
DROP SEQUENCE UNI_CONTENT_VERSION_SEC;
DROP TABLE UNI_TOOL_VERSION;
DROP SEQUENCE UNI_TOOL_VERSION_SEC;
DROP TABLE UNI_MODULE_REG;
DROP SEQUENCE UNI_MODULE_REG_SEC;
DROP TABLE UNI_DEVICE_REG;
DROP SEQUENCE UNI_DEVICE_REG_SEC;
DROP TABLE UNI_MANAGED_MODULE;
DROP SEQUENCE UNI_MANAGED_MODULE_SEC;
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
COMMIT;
