--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--
--  Insert statements for the test data in the Unipoole database.
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--

--------------------------------------------------------
--  Base data insert for Table UNI_MANAGED_MODULE
--------------------------------------------------------
DELETE FROM UNI_MANAGED_MODULE WHERE ID = 1;
INSERT INTO UNI_MANAGED_MODULE (ID, MODULE_ID, ACTIVE, LAST_UPDATED) VALUES(
    1, 'AFL1501-13-S1', 1, CURRENT_DATE);
SELECT UNI_MANAGED_MODULE_SEC.nextval FROM dual;
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--------------------------------------------------------
--  Base data insert for Table UNI_MODULE_REG
--------------------------------------------------------
DELETE FROM UNI_MODULE_REG WHERE ID = 1;
INSERT INTO UNI_MODULE_REG (ID, DEVICE_REGISTRATION_ID, MODULE_ID, ACTIVE, LAST_UPDATED) VALUES(
    1, 1, 'MASTER', 1, CURRENT_DATE);
SELECT UNI_MODULE_REG_SEC.nextval FROM dual;
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--------------------------------------------------------
--  Base data insert for Table UNI_TOOL_VERSION
--------------------------------------------------------
UPDATE UNI_TOOL_VERSION SET ACTIVE = 0
    WHERE DEVICE_REGISTRATION_ID = 1;
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'client.base', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.home', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.melete', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.yaft', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.announcements', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'unisa.welcome', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.samigo', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.resources', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'sakai.schedule', '1.0.0', 1, CURRENT_DATE);
INSERT INTO UNI_TOOL_VERSION (ID, DEVICE_REGISTRATION_ID, TOOL_NAME, TOOL_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_TOOL_VERSION_SEC.nextval, 1, 'unisa.faq', '1.0.0', 1, CURRENT_DATE);
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--------------------------------------------------------
--  Base data insert for Table UNI_CONTENT_VERSION
--------------------------------------------------------
DELETE FROM UNI_CONTENT_VERSION WHERE MODULE_REGISTRATION_ID = 1;
INSERT INTO UNI_CONTENT_VERSION (ID, MODULE_REGISTRATION_ID, TOOL_NAME, CONTENT_VERSION, ACTIVE, LAST_UPDATED) VALUES(
    UNI_CONTENT_VERSION_SEC.nextval, 1, 'client.base', '1.0.0', 1, CURRENT_DATE);
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
COMMIT;
