--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--
--  Test statements for duplicates.
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--

--------------------------------------------------------
--  UNI_CONTENT_VERSION
--------------------------------------------------------
SELECT * FROM (
SELECT COUNT(*) AS COUNT, CV.MODULE_REGISTRATION_ID, CV.TOOL_NAME, CV.ACTIVE 
FROM UNI_CONTENT_VERSION CV
WHERE CV.ACTIVE = 1
GROUP BY CV.MODULE_REGISTRATION_ID, CV.TOOL_NAME, CV.ACTIVE)
WHERE COUNT > 1;

--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--------------------------------------------------------
--  UNI_TOOL_VERSION
--------------------------------------------------------
SELECT * FROM (
SELECT COUNT(*) AS COUNT, TV.DEVICE_REGISTRATION_ID, TV.TOOL_NAME, TV.ACTIVE 
FROM UNI_TOOL_VERSION TV
WHERE TV.ACTIVE = 1
GROUP BY TV.DEVICE_REGISTRATION_ID, TV.TOOL_NAME, TV.ACTIVE)
WHERE COUNT > 1;

--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
--------------------------------------------------------
--  UNI_CONTENT_RELEASE
--------------------------------------------------------
SELECT * FROM (
SELECT COUNT(*) AS COUNT, CR.MODULE_ID, CR.ACTIVE
FROM UNI_CONTENT_RELEASE CR
WHERE CR.ACTIVE = 1
GROUP BY CR.MODULE_ID, CR.ACTIVE)
WHERE COUNT > 1;
